package com.botzap.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InteracaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInteracaoAllPropertiesEquals(Interacao expected, Interacao actual) {
        assertInteracaoAutoGeneratedPropertiesEquals(expected, actual);
        assertInteracaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInteracaoAllUpdatablePropertiesEquals(Interacao expected, Interacao actual) {
        assertInteracaoUpdatableFieldsEquals(expected, actual);
        assertInteracaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInteracaoAutoGeneratedPropertiesEquals(Interacao expected, Interacao actual) {
        assertThat(expected)
            .as("Verify Interacao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInteracaoUpdatableFieldsEquals(Interacao expected, Interacao actual) {
        assertThat(expected)
            .as("Verify Interacao relevant properties")
            .satisfies(e -> assertThat(e.getDataHora()).as("check dataHora").isEqualTo(actual.getDataHora()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInteracaoUpdatableRelationshipsEquals(Interacao expected, Interacao actual) {
        assertThat(expected)
            .as("Verify Interacao relationships")
            .satisfies(e -> assertThat(e.getUsuario()).as("check usuario").isEqualTo(actual.getUsuario()))
            .satisfies(e -> assertThat(e.getMensagem()).as("check mensagem").isEqualTo(actual.getMensagem()));
    }
}
