package com.botzap.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MensagemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensagemAllPropertiesEquals(Mensagem expected, Mensagem actual) {
        assertMensagemAutoGeneratedPropertiesEquals(expected, actual);
        assertMensagemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensagemAllUpdatablePropertiesEquals(Mensagem expected, Mensagem actual) {
        assertMensagemUpdatableFieldsEquals(expected, actual);
        assertMensagemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensagemAutoGeneratedPropertiesEquals(Mensagem expected, Mensagem actual) {
        assertThat(expected)
            .as("Verify Mensagem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensagemUpdatableFieldsEquals(Mensagem expected, Mensagem actual) {
        assertThat(expected)
            .as("Verify Mensagem relevant properties")
            .satisfies(e -> assertThat(e.getTexto()).as("check texto").isEqualTo(actual.getTexto()))
            .satisfies(e -> assertThat(e.getOpcao()).as("check opcao").isEqualTo(actual.getOpcao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensagemUpdatableRelationshipsEquals(Mensagem expected, Mensagem actual) {
        assertThat(expected)
            .as("Verify Mensagem relationships")
            .satisfies(e -> assertThat(e.getFluxo()).as("check fluxo").isEqualTo(actual.getFluxo()));
    }
}
