package com.botzap.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SeguinteMensagemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguinteMensagemAllPropertiesEquals(SeguinteMensagem expected, SeguinteMensagem actual) {
        assertSeguinteMensagemAutoGeneratedPropertiesEquals(expected, actual);
        assertSeguinteMensagemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguinteMensagemAllUpdatablePropertiesEquals(SeguinteMensagem expected, SeguinteMensagem actual) {
        assertSeguinteMensagemUpdatableFieldsEquals(expected, actual);
        assertSeguinteMensagemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguinteMensagemAutoGeneratedPropertiesEquals(SeguinteMensagem expected, SeguinteMensagem actual) {
        assertThat(expected)
            .as("Verify SeguinteMensagem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguinteMensagemUpdatableFieldsEquals(SeguinteMensagem expected, SeguinteMensagem actual) {
        assertThat(expected)
            .as("Verify SeguinteMensagem relevant properties")
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeguinteMensagemUpdatableRelationshipsEquals(SeguinteMensagem expected, SeguinteMensagem actual) {
        // empty method
    }
}
